version: '2'

services:

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./src:/var/www/html
    links:
      - dbserver
    ports:
      - 8080:80

  dbserver:
    build:
      context: ./
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 32780:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
